# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*/

install:
  - cinst pester
  - ps: Install-PackageProvider -Name NuGet -Force
  â€“ ps: Install-Module -Name PSScriptAnalyzer -Force

build: false

test_script:
# Test with native PS version
  - ps: . .\appveyor.pester.ps1
# Finalize pass - collect and upload results
  - ps: . .\appveyor.pester.ps1 -Finalize

deploy:
# Code to push to PS Gallery here. Assuming this only happens if tests pass, otherwise maybe need to use on_success?
